import { getDb } from '../db/connection.js';

/**
 * Cover images are generated by scripts/optimize-images.mjs into
 * client/public/images/covers/<slug>-{200,400}.{webp,jpg}.
 */
function coverFor(coverSlug, title) {
  const base = `/images/covers/${coverSlug}`;
  return {
    src: `${base}-400.webp`,
    srcSet: `${base}-200.webp 200w, ${base}-400.webp 400w`,
    fallback: `${base}-400.jpg`,
    width: 400,
    height: 400,
    alt: `${title} playlist cover art`,
  };
}

function trackUrl(folder, fileName) {
  return `/media/music/${encodeURIComponent(folder)}/${encodeURIComponent(fileName)}`;
}

const TRACK_SELECT = `
  SELECT t.id, t.title, t.artist, t.position, t.file_name,
         p.slug AS playlist_slug, p.title AS playlist_title, p.folder
    FROM tracks t
    JOIN playlists p ON p.id = t.playlist_id`;

export function toTrack(row) {
  return {
    id: row.id,
    title: row.title,
    artist: row.artist,
    url: trackUrl(row.folder, row.file_name),
    position: row.position,
    playlistSlug: row.playlist_slug,
    playlistTitle: row.playlist_title,
  };
}

function toPlaylistSummary(row) {
  return {
    id: row.id,
    slug: row.slug,
    title: row.title,
    description: row.description,
    cover: coverFor(row.cover_slug, row.title),
    trackCount: row.track_count,
    href: `/playlist/${row.slug}`,
  };
}

export function listPlaylists() {
  const rows = getDb()
    .prepare(
      `SELECT p.*, (SELECT COUNT(*) FROM tracks t WHERE t.playlist_id = p.id) AS track_count
         FROM playlists p
        ORDER BY p.position, p.id`,
    )
    .all();
  return rows.map(toPlaylistSummary);
}

export function getPlaylistBySlug(slug) {
  const db = getDb();
  const row = db
    .prepare(
      `SELECT p.*, (SELECT COUNT(*) FROM tracks t WHERE t.playlist_id = p.id) AS track_count
         FROM playlists p WHERE p.slug = ?`,
    )
    .get(slug);
  if (!row) return null;

  const tracks = db
    .prepare(`${TRACK_SELECT} WHERE t.playlist_id = ? ORDER BY t.position, t.id`)
    .all(row.id)
    .map(toTrack);

  return { ...toPlaylistSummary(row), tracks };
}

export function playlistExists(slug) {
  return Boolean(getDb().prepare('SELECT 1 FROM playlists WHERE slug = ?').get(slug));
}

/** Every track in the catalogue, grouped order = playlist position then track position. */
export function listAllTracks() {
  return getDb()
    .prepare(`${TRACK_SELECT} ORDER BY p.position, p.id, t.position, t.id`)
    .all()
    .map(toTrack);
}

/** Fetch tracks by id, preserving the order of `ids`. Unknown ids are skipped. */
export function getTracksByIds(ids) {
  if (!ids.length) return [];
  const placeholders = ids.map(() => '?').join(',');
  const rows = getDb().prepare(`${TRACK_SELECT} WHERE t.id IN (${placeholders})`).all(...ids);
  const byId = new Map(rows.map((r) => [r.id, toTrack(r)]));
  return ids.map((id) => byId.get(id)).filter(Boolean);
}
